# Generated by Django 5.2.17 on 2026-09-01 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_alter_organisation_storage_limit_bytes'),
        ('workorders', '0002_workorder_assignment_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('assignment_revision', models.PositiveIntegerField()),
                ('deduplication_key', models.CharField(max_length=160, unique=True)),
                ('provider_idempotency_key', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('retrying', 'Retrying'), ('delivered', 'Delivered'), ('permanently_failed', 'Permanently failed')], db_index=True, default='queued', max_length=30)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organisations.organisation')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to='organisations.organisationuser')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to='workorders.workorder')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('delivered', 'Delivered'), ('temporary_failure', 'Temporary failure'), ('permanent_failure', 'Permanent failure')], max_length=30)),
                ('diagnostic', models.CharField(blank=True, max_length=500)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organisations.organisation')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='notifications.notificationdelivery')),
            ],
            options={
                'ordering': ('attempt_number',),
            },
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['organisation', 'status', 'created_at'], name='notificatio_organis_ef9a61_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['organisation', 'technician', 'created_at'], name='notificatio_organis_bb1c97_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('work_order', 'assignment_revision'), name='unique_notification_per_assignment_revision'),
        ),
        migrations.AddConstraint(
            model_name='notificationattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'attempt_number'), name='unique_notification_attempt_number'),
        ),
    ]
