# Generated by Django 5.2.17 on 2026-09-01 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='organisationuser',
            index=models.Index(fields=['organisation', 'role', 'is_active'], name='organisatio_organis_d273b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='organisationuser',
            constraint=models.UniqueConstraint(fields=('organisation', 'user'), name='unique_user_per_organisation'),
        ),
    ]
