# Generated by Django 5.2.17 on 2026-09-01 18:11

import django.core.validators
import organisations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='storage_limit_bytes',
            field=models.PositiveBigIntegerField(default=organisations.models.default_storage_limit_bytes, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
