# Generated by Django 5.2.17 on 2026-09-01 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('status_changed', 'Status changed'), ('note_added', 'Note added')], max_length=30)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField()),
                ('original_event', models.JSONField()),
                ('request_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_progress_events', to='organisations.organisationuser')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organisations.organisation')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_events', to='workorders.workorder')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['organisation', 'work_order', 'occurred_at'], name='progress_ev_organis_0cf031_idx'), models.Index(fields=['organisation', 'actor', 'occurred_at'], name='progress_ev_organis_100e78_idx')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'event_id'), name='unique_progress_event_id_per_organisation')],
            },
        ),
    ]
