# Generated by Django 5.2.17 on 2026-09-01 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('reference_number', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('site_name', models.CharField(max_length=200)),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to='organisations.organisationuser')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to='organisations.organisationuser')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['organisation', 'status', 'created_at'], name='workorders__organis_d5a9d8_idx'), models.Index(fields=['organisation', 'priority', 'created_at'], name='workorders__organis_f8e6d5_idx'), models.Index(fields=['organisation', 'assigned_technician', 'scheduled_start'], name='workorders__organis_44c5bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'reference_number'), name='unique_work_order_reference_per_organisation'), models.CheckConstraint(condition=models.Q(models.Q(('scheduled_end__isnull', True), ('scheduled_start__isnull', True)), models.Q(('scheduled_end__isnull', False), ('scheduled_start__isnull', False)), _connector='OR'), name='work_order_schedule_window_is_paired'), models.CheckConstraint(condition=models.Q(('scheduled_start__isnull', True), ('scheduled_end__gt', models.F('scheduled_start')), _connector='OR'), name='work_order_schedule_end_after_start')],
            },
        ),
    ]
