# Generated by Django 5.2.17 on 2026-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assignment_revision',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
