import { useState, type FormEvent, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, Navigate, NavLink, Route, Routes, useNavigate, useParams } from "react-router-dom";

import { ApiError, apiPage, apiRequest, downloadAuthenticated } from "./api";
import { useAuth } from "./auth";
import { useRealtime } from "./realtime";
import type { Attachment, AuditEntry, DashboardSummary, Organisation, OrganisationUser, WorkOrder } from "./types";

const STATUS_LABELS: Record<WorkOrder["status"], string> = { draft: "Draft", scheduled: "Scheduled", in_progress: "In progress", blocked: "Blocked", completed: "Completed", cancelled: "Cancelled" };
const PRIORITY_LABELS: Record<WorkOrder["priority"], string> = { low: "Low", medium: "Medium", high: "High", urgent: "Urgent" };
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const formatBytes = (value: number) => value < 1024 ? `${value} B` : value < 1024 ** 2 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1024 ** 2).toFixed(1)} MB`;
const errorMessage = (error: unknown) => error instanceof Error ? error.message : "Something went wrong. Please try again.";

function Spinner({ label = "Loading" }: { label?: string }) { return <div className="state-panel"><span className="spinner" /><span>{label}…</span></div>; }
function ErrorPanel({ error }: { error: unknown }) { const apiError = error instanceof ApiError ? error : null; return <div className="alert alert-error" role="alert"><strong>{apiError?.code === "SCHEDULE_CONFLICT" ? "Scheduling conflict" : "Unable to continue"}</strong><span>{errorMessage(error)}</span></div>; }
function StatusBadge({ status }: { status: WorkOrder["status"] }) { return <span className={`badge status-${status}`}>{STATUS_LABELS[status]}</span>; }
function PriorityBadge({ priority }: { priority: WorkOrder["priority"] }) { return <span className={`priority priority-${priority}`}>{PRIORITY_LABELS[priority]}</span>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty-state"><span>□</span><h3>{title}</h3><p>{text}</p></div>; }

function LoginPage() {
  const { login, session } = useAuth(); const navigate = useNavigate();
  const [email, setEmail] = useState("dispatcher@northstar.test"); const [password, setPassword] = useState("FieldDeskDemo!2026");
  const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  if (session) return <Navigate to="/dashboard" replace />;
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setSubmitting(true); try { await login(email, password); navigate("/dashboard", { replace: true }); } catch (reason) { setError(errorMessage(reason)); } finally { setSubmitting(false); } };
  return <main className="login-page"><section className="login-brand"><div className="brand-mark large">FD</div><p className="eyebrow">Field service operations</p><h1>Keep every field job moving.</h1><p>Plan work, coordinate technicians and retain a complete operational history in one secure workspace.</p><div className="login-proof"><span>✓ Tenant isolated</span><span>✓ Realtime operations</span><span>✓ Audit ready</span></div></section><section className="login-panel" aria-labelledby="login-title"><div className="mobile-brand"><span className="brand-mark">FD</span><strong>FieldDesk</strong></div><p className="eyebrow">Welcome back</p><h2 id="login-title">Sign in to FieldDesk</h2><p className="muted">Use your organisation account to continue.</p>{error && <div className="alert alert-error" role="alert">{error}</div>}<form onSubmit={submit} className="form-stack"><label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label><button className="button button-primary button-wide" disabled={submitting}>{submitting ? "Signing in…" : "Sign in"}</button></form><div className="demo-note"><strong>Reviewer account</strong><span>Dispatcher credentials are prefilled for local seed data.</span></div></section></main>;
}

function AppShell({ children }: { children: ReactNode }) {
  const { session, logout, token } = useAuth(); const [mobileOpen, setMobileOpen] = useState(false); useRealtime(Boolean(token));
  if (!session) return <Navigate to="/login" replace />;
  const manager = session.role !== "technician";
  const nav = [["/dashboard", "Overview", "▦"], ["/work-orders", "Work orders", "▤"], ...(session.role === "owner" ? [["/users", "People & roles", "♙"], ["/organisation", "Organisation", "◫"]] : [])];
  return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? "open" : ""}`}><div className="sidebar-brand"><span className="brand-mark">FD</span><span><strong>FieldDesk</strong><small>Operations ERP</small></span></div><nav>{nav.map(([to, label, icon]) => <NavLink key={to} to={to} onClick={() => setMobileOpen(false)}><span>{icon}</span>{label}</NavLink>)}</nav><div className="sidebar-bottom"><div className="org-chip"><span>{session.organisation.name.slice(0, 2).toUpperCase()}</span><div><strong>{session.organisation.name}</strong><small>{session.role}</small></div></div><button className="nav-button" onClick={() => void logout()}><span>↪</span> Sign out</button></div></aside>{mobileOpen && <button className="scrim" aria-label="Close navigation" onClick={() => setMobileOpen(false)} />}<div className="workspace"><header className="topbar"><button className="icon-button menu-button" aria-label="Open navigation" onClick={() => setMobileOpen(true)}>☰</button><div><strong>{session.organisation.name}</strong><span className="environment-dot">Live</span></div><div className="topbar-actions">{manager && <Link className="button button-primary button-small" to="/work-orders/new">+ New work order</Link>}<div className="avatar">{(session.user.firstName[0] || session.user.email[0]).toUpperCase()}</div></div></header><main className="main-content">{children}</main></div></div>;
}

function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description?: string; actions?: ReactNode }) { return <header className="page-header"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <div className="page-actions">{actions}</div>}</header>; }
function Kpi({ label, value, detail, tone }: { label: string; value: number; detail: string; tone: string }) { return <article className={`kpi-card ${tone}`}><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div><div className="kpi-icon">↗</div></article>; }
function ReportButton() { const { session } = useAuth(); const [busy, setBusy] = useState(false); if (session?.role === "technician") return null; return <button className="button button-secondary" disabled={busy} onClick={async () => { setBusy(true); try { await downloadAuthenticated("/reports/work-orders.csv", "fielddesk-work-orders.csv"); } finally { setBusy(false); } }}>{busy ? "Preparing…" : "⇩ Export CSV"}</button>; }

function DashboardPage() {
  const { session } = useAuth(); const summary = useQuery({ queryKey: ["dashboard"], queryFn: () => apiRequest<DashboardSummary>("/dashboard/summary") }); const recent = useQuery({ queryKey: ["work-orders", "recent"], queryFn: () => apiPage<WorkOrder>("/work-orders?pageSize=6&ordering=-updatedAt") });
  if (summary.isLoading) return <Spinner label="Loading operations dashboard" />; if (summary.error) return <ErrorPanel error={summary.error} />; const data = summary.data!;
  return <><PageHeader eyebrow="Operations overview" title={`Good ${new Date().getHours() < 12 ? "morning" : "afternoon"}, ${session?.user.firstName || "team"}`} description="A live view of workload, technician allocation and service progress." actions={session?.role !== "technician" && <ReportButton />} /><section className="kpi-grid"><Kpi label="Total work orders" value={data.total} detail={`${data.assigned} assigned`} tone="navy" /><Kpi label="In progress" value={data.byStatus.in_progress} detail={`${data.byStatus.blocked} blocked`} tone="blue" /><Kpi label="Scheduled" value={data.byStatus.scheduled} detail={`${data.unassigned} unassigned`} tone="amber" /><Kpi label="Completed" value={data.byStatus.completed} detail={`${data.byPriority.urgent} urgent`} tone="green" /></section><section className="dashboard-grid"><div className="panel span-2"><div className="panel-heading"><div><h2>Recent work orders</h2><p>Latest operational changes</p></div><Link to="/work-orders">View all →</Link></div>{recent.isLoading ? <Spinner /> : recent.data?.data.length ? <WorkOrderTable orders={recent.data.data} compact /> : <Empty title="No work orders yet" text="Create the first work order to start planning field activity." />}</div><div className="panel"><div className="panel-heading"><div><h2>Status mix</h2><p>Current workload</p></div></div><div className="status-breakdown">{Object.entries(data.byStatus).map(([status, count]) => <div key={status}><div><StatusBadge status={status as WorkOrder["status"]} /><strong>{count}</strong></div><span><i style={{ width: `${data.total ? Math.max(4, (count / data.total) * 100) : 0}%` }} /></span></div>)}</div></div></section></>;
}

function WorkOrdersPage() {
  const { session } = useAuth(); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [priority, setPriority] = useState(""); const [ordering, setOrdering] = useState("-createdAt"); const [page, setPage] = useState(1);
  const query = new URLSearchParams({ page: String(page), pageSize: "20", ordering }); if (search) query.set("search", search); if (status) query.set("status", status); if (priority) query.set("priority", priority);
  const orders = useQuery({ queryKey: ["work-orders", query.toString()], queryFn: () => apiPage<WorkOrder>(`/work-orders?${query}`) });
  return <><PageHeader eyebrow="Service operations" title="Work orders" description={session?.role === "technician" ? "Work assigned to you." : "Plan, assign and track every field-service job."} actions={<div className="page-actions"><ReportButton />{session?.role !== "technician" && <Link className="button button-primary" to="/work-orders/new">+ New work order</Link>}</div>} /><section className="panel"><div className="filter-bar"><label className="search-field"><span>⌕</span><input aria-label="Search work orders" placeholder="Search reference, title or site…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></label><select aria-label="Filter status" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">All statuses</option>{Object.entries(STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Filter priority" value={priority} onChange={(e) => { setPriority(e.target.value); setPage(1); }}><option value="">All priorities</option>{Object.entries(PRIORITY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Sort work orders" value={ordering} onChange={(e) => setOrdering(e.target.value)}><option value="-createdAt">Newest first</option><option value="createdAt">Oldest first</option><option value="referenceNumber">Reference</option><option value="-scheduledStart">Latest schedule</option><option value="priority">Priority</option></select></div>{orders.isLoading ? <Spinner label="Loading work orders" /> : orders.error ? <ErrorPanel error={orders.error} /> : orders.data?.data.length ? <><WorkOrderTable orders={orders.data.data} /><Pagination page={orders.data.meta.page} totalPages={orders.data.meta.totalPages} total={orders.data.meta.total} onPage={setPage} /></> : <Empty title="No matching work orders" text="Adjust your filters or create a new service job." />}</section></>;
}

function WorkOrderTable({ orders, compact = false }: { orders: WorkOrder[]; compact?: boolean }) { return <div className="table-wrap"><table><thead><tr><th>Work order</th><th>Status</th><th>Priority</th><th>Technician</th>{!compact && <th>Scheduled</th>}<th /></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><Link className="record-link" to={`/work-orders/${order.id}`}><strong>{order.referenceNumber}</strong><span>{order.title}</span><small>{order.siteName}</small></Link></td><td><StatusBadge status={order.status} /></td><td><PriorityBadge priority={order.priority} /></td><td>{order.assignedTechnician ? <div className="person-cell"><span>{order.assignedTechnician.fullName.slice(0, 1)}</span><div>{order.assignedTechnician.fullName}<small>{order.assignedTechnician.email}</small></div></div> : <span className="muted">Unassigned</span>}</td>{!compact && <td>{formatDate(order.scheduledStart)}</td>}<td><Link className="row-arrow" to={`/work-orders/${order.id}`}>›</Link></td></tr>)}</tbody></table></div>; }
function Pagination({ page, totalPages, total, onPage }: { page: number; totalPages: number; total: number; onPage: (page: number) => void }) { return <div className="pagination"><span>{total} results</span><div><button disabled={page <= 1} onClick={() => onPage(page - 1)}>← Previous</button><span>Page {page} of {Math.max(totalPages, 1)}</span><button disabled={page >= totalPages} onClick={() => onPage(page + 1)}>Next →</button></div></div>; }

function WorkOrderFormPage({ edit = false }: { edit?: boolean }) {
  const { id } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient(); const existing = useQuery({ queryKey: ["work-order", id], queryFn: () => apiRequest<WorkOrder>(`/work-orders/${id}`), enabled: edit });
  const [values, setValues] = useState({ title: "", description: "", siteName: "", priority: "medium", status: "draft" }); const [hydrated, setHydrated] = useState(false);
  if (edit && existing.data && !hydrated) { setValues({ title: existing.data.title, description: existing.data.description, siteName: existing.data.siteName, priority: existing.data.priority, status: existing.data.status }); setHydrated(true); }
  const mutation = useMutation({ mutationFn: () => apiRequest<WorkOrder>(edit ? `/work-orders/${id}` : "/work-orders", { method: edit ? "PATCH" : "POST", body: edit ? values : { title: values.title, description: values.description, siteName: values.siteName, priority: values.priority } }), onSuccess: (order) => { void queryClient.invalidateQueries({ queryKey: ["work-orders"] }); navigate(`/work-orders/${order.id}`); } });
  if (edit && existing.isLoading) return <Spinner />;
  return <><PageHeader eyebrow="Work orders" title={edit ? "Edit work order" : "Create work order"} description={edit ? `Update ${existing.data?.referenceNumber ?? "work order"} details.` : "Capture the service requirement before assigning a technician."} /><form className="panel form-panel" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}>{mutation.error && <ErrorPanel error={mutation.error} />}<div className="form-grid"><label className="span-2">Title<input required maxLength={200} value={values.title} onChange={(e) => setValues({ ...values, title: e.target.value })} placeholder="e.g. Repair rooftop cooling unit" /></label><label>Site name<input required value={values.siteName} onChange={(e) => setValues({ ...values, siteName: e.target.value })} /></label><label>Priority<select value={values.priority} onChange={(e) => setValues({ ...values, priority: e.target.value })}>{Object.entries(PRIORITY_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{edit && <label>Status<select value={values.status} onChange={(e) => setValues({ ...values, status: e.target.value })}>{Object.entries(STATUS_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}<label className="span-2">Description<textarea rows={7} value={values.description} onChange={(e) => setValues({ ...values, description: e.target.value })} /></label></div><div className="form-actions"><button type="button" className="button button-ghost" onClick={() => navigate(-1)}>Cancel</button><button className="button button-primary" disabled={mutation.isPending}>{mutation.isPending ? "Saving…" : edit ? "Save changes" : "Create work order"}</button></div></form></>;
}

function WorkOrderDetailPage() {
  const { id } = useParams(); const { session } = useAuth(); const order = useQuery({ queryKey: ["work-order", id], queryFn: () => apiRequest<WorkOrder>(`/work-orders/${id}`) });
  if (order.isLoading) return <Spinner label="Loading work order" />; if (order.error || !order.data) return <ErrorPanel error={order.error} />; const item = order.data;
  return <><div className="breadcrumb"><Link to="/work-orders">Work orders</Link><span>›</span><span>{item.referenceNumber}</span></div><PageHeader title={item.title} description={`${item.referenceNumber} · ${item.siteName}`} actions={<div className="page-actions">{session?.role !== "technician" && <Link className="button button-secondary" to={`/work-orders/${item.id}/edit`}>Edit details</Link>}<StatusBadge status={item.status} /></div>} /><section className="detail-grid"><div className="detail-main"><div className="panel"><div className="panel-heading"><div><h2>Job information</h2><p>Scope and service details</p></div></div><dl className="detail-list"><div><dt>Description</dt><dd>{item.description || "No description provided."}</dd></div><div><dt>Site</dt><dd>{item.siteName}</dd></div><div><dt>Priority</dt><dd><PriorityBadge priority={item.priority} /></dd></div><div><dt>Created by</dt><dd>{item.creator.fullName}<small>{formatDate(item.createdAt)}</small></dd></div></dl></div>{session?.role !== "technician" ? <SchedulePanel order={item} /> : <ProgressPanel order={item} />}<AttachmentsPanel order={item} /><ActivityPanel orderId={item.id} /></div><aside className="detail-side"><div className="panel sticky-panel"><h2>Assignment</h2><div className="assignment-card">{item.assignedTechnician ? <><div className="large-avatar">{item.assignedTechnician.fullName[0]}</div><strong>{item.assignedTechnician.fullName}</strong><span>{item.assignedTechnician.email}</span></> : <><div className="large-avatar empty">?</div><strong>Not assigned</strong><span>Choose a technician and schedule.</span></>}</div><dl className="compact-list"><div><dt>Starts</dt><dd>{formatDate(item.scheduledStart)}</dd></div><div><dt>Ends</dt><dd>{formatDate(item.scheduledEnd)}</dd></div><div><dt>Last updated</dt><dd>{formatDate(item.updatedAt)}</dd></div></dl></div></aside></section></>;
}

function SchedulePanel({ order }: { order: WorkOrder }) {
  const queryClient = useQueryClient(); const users = useQuery({ queryKey: ["technicians"], queryFn: () => apiRequest<OrganisationUser[]>("/users/") }); const local = (value: string | null) => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : "";
  const [technicianId, setTechnicianId] = useState(order.assignedTechnician?.id ?? ""); const [start, setStart] = useState(local(order.scheduledStart)); const [end, setEnd] = useState(local(order.scheduledEnd));
  const mutation = useMutation({ mutationFn: () => apiRequest<WorkOrder>(`/work-orders/${order.id}/assign`, { method: "POST", body: { technicianId, scheduledStart: new Date(start).toISOString(), scheduledEnd: new Date(end).toISOString() } }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["work-order", order.id] }); void queryClient.invalidateQueries({ queryKey: ["work-orders"] }); } });
  return <div className="panel"><div className="panel-heading"><div><h2>Schedule & assignment</h2><p>PostgreSQL prevents overlapping technician schedules.</p></div></div>{mutation.error && <ErrorPanel error={mutation.error} />}<form className="inline-form" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}><label>Technician<select required value={technicianId} onChange={(e) => setTechnicianId(e.target.value)}><option value="">Select technician</option>{users.data?.filter((user) => user.role === "technician" && user.isActive).map((user) => <option key={user.id} value={user.id}>{user.fullName} · {user.email}</option>)}</select></label><label>Start<input required type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} /></label><label>End<input required type="datetime-local" value={end} onChange={(e) => setEnd(e.target.value)} /></label><button className="button button-primary" disabled={mutation.isPending}>{mutation.isPending ? "Scheduling…" : order.assignedTechnician ? "Update schedule" : "Assign work"}</button></form></div>;
}

function ProgressPanel({ order }: { order: WorkOrder }) {
  const queryClient = useQueryClient(); const [status, setStatus] = useState("in_progress"); const [note, setNote] = useState(""); const mutation = useMutation({ mutationFn: () => apiRequest("/progress-events", { method: "POST", body: { eventId: crypto.randomUUID(), workOrderId: order.id, type: "status_changed", occurredAt: new Date().toISOString(), payload: { status, ...(note ? { note } : {}) } } }), onSuccess: () => { setNote(""); void queryClient.invalidateQueries({ queryKey: ["work-order", order.id] }); } });
  return <div className="panel"><div className="panel-heading"><div><h2>Submit progress</h2><p>Update field status with an optional note.</p></div></div>{mutation.error && <ErrorPanel error={mutation.error} />}<form className="inline-form progress-form" onSubmit={(e) => { e.preventDefault(); mutation.mutate(); }}><label>New status<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></label><label className="grow">Progress note<input value={note} maxLength={1000} onChange={(e) => setNote(e.target.value)} placeholder="What changed on site?" /></label><button className="button button-primary" disabled={mutation.isPending}>{mutation.isPending ? "Submitting…" : "Submit update"}</button></form></div>;
}

function AttachmentsPanel({ order }: { order: WorkOrder }) {
  const { session } = useAuth(); const queryClient = useQueryClient(); const attachments = useQuery({ queryKey: ["attachments", order.id], queryFn: () => apiRequest<Attachment[]>(`/work-orders/${order.id}/attachments`) }); const upload = useMutation({ mutationFn: (file: File) => { const body = new FormData(); body.append("file", file); return apiRequest<Attachment>(`/work-orders/${order.id}/attachments`, { method: "POST", body }); }, onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["attachments", order.id] }) }); const remove = useMutation({ mutationFn: (fileId: string) => apiRequest(`/work-orders/${order.id}/attachments/${fileId}`, { method: "DELETE" }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["attachments", order.id] }) });
  return <div className="panel"><div className="panel-heading"><div><h2>Attachments</h2><p>Private JPEG, PNG and PDF evidence.</p></div><label className="button button-secondary file-button">+ Upload<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={(e) => { const file = e.target.files?.[0]; if (file) upload.mutate(file); e.target.value = ""; }} /></label></div>{upload.error && <ErrorPanel error={upload.error} />}{attachments.isLoading ? <Spinner /> : attachments.data?.length ? <div className="attachment-list">{attachments.data.map((file) => <div key={file.id}><span className="file-icon">{file.contentType === "application/pdf" ? "PDF" : "IMG"}</span><div><strong>{file.fileName}</strong><small>{formatBytes(file.sizeBytes)} · {formatDate(file.createdAt)}</small></div><button className="text-button" onClick={() => void downloadAuthenticated(file.downloadUrl.replace("/api/v1", ""), file.fileName)}>Download</button>{session?.role !== "technician" && <button className="icon-button danger" onClick={() => remove.mutate(file.id)}>×</button>}</div>)}</div> : <Empty title="No attachments" text="Upload photos or a PDF service document." />}</div>;
}

function ActivityPanel({ orderId }: { orderId: string }) { const activity = useQuery({ queryKey: ["activity", orderId], queryFn: () => apiPage<AuditEntry>(`/work-orders/${orderId}/activity?pageSize=50`) }); return <div className="panel"><div className="panel-heading"><div><h2>Activity history</h2><p>Immutable operational record</p></div></div>{activity.isLoading ? <Spinner /> : activity.data?.data.length ? <div className="timeline">{activity.data.data.map((entry) => <div key={entry.id}><span className="timeline-dot" /><div><strong>{entry.action.split(".").map((part) => part[0].toUpperCase() + part.slice(1)).join(" ")}</strong><p>{entry.actor?.name || "FieldDesk system"} · {formatDate(entry.createdAt)}</p>{Object.keys(entry.metadata).length > 0 && <small>{Object.entries(entry.metadata).slice(0, 2).map(([key, value]) => `${key}: ${String(value)}`).join(" · ")}</small>}</div></div>)}</div> : <Empty title="No activity recorded" text="Material changes will appear here." />}</div>; }

function UsersPage() {
  const queryClient = useQueryClient(); const users = useQuery({ queryKey: ["users"], queryFn: () => apiRequest<OrganisationUser[]>("/users/") }); const [showCreate, setShowCreate] = useState(false); const [form, setForm] = useState({ email: "", firstName: "", lastName: "", password: "", role: "technician" }); const create = useMutation({ mutationFn: () => apiRequest("/users/", { method: "POST", body: form }), onSuccess: () => { setShowCreate(false); void queryClient.invalidateQueries({ queryKey: ["users"] }); } }); const update = useMutation({ mutationFn: ({ id, body }: { id: string; body: unknown }) => apiRequest(`/users/${id}`, { method: "PATCH", body }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["users"] }) });
  return <><PageHeader eyebrow="Administration" title="People & roles" description="Manage access and operational responsibilities." actions={<button className="button button-primary" onClick={() => setShowCreate(!showCreate)}>+ Add user</button>} />{showCreate && <form className="panel inline-create" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}>{create.error && <ErrorPanel error={create.error} />}<div className="form-grid"><label>First name<input required value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} /></label><label>Last name<input value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="technician">Technician</option><option value="dispatcher">Dispatcher</option><option value="owner">Owner</option></select></label><label className="span-2">Temporary password<input required type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label></div><div className="form-actions"><button type="button" className="button button-ghost" onClick={() => setShowCreate(false)}>Cancel</button><button className="button button-primary">Create user</button></div></form>}<section className="panel">{users.isLoading ? <Spinner /> : users.error ? <ErrorPanel error={users.error} /> : <div className="table-wrap"><table><thead><tr><th>Person</th><th>Role</th><th>Status</th><th>Created</th><th /></tr></thead><tbody>{users.data?.map((user) => <tr key={user.id}><td><div className="person-cell"><span>{user.firstName[0] || user.email[0]}</span><div><strong>{user.fullName || user.email}</strong><small>{user.email}</small></div></div></td><td><select className="table-select" value={user.role} onChange={(e) => update.mutate({ id: user.id, body: { role: e.target.value } })}><option value="owner">Owner</option><option value="dispatcher">Dispatcher</option><option value="technician">Technician</option></select></td><td><span className={`badge ${user.isActive ? "status-completed" : "status-cancelled"}`}>{user.isActive ? "Active" : "Inactive"}</span></td><td>{formatDate(user.createdAt)}</td><td><button className="text-button" onClick={() => update.mutate({ id: user.id, body: { isActive: !user.isActive } })}>{user.isActive ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table></div>}</section></>;
}

function OrganisationPage() {
  const queryClient = useQueryClient(); const organisation = useQuery({ queryKey: ["organisation"], queryFn: () => apiRequest<Organisation>("/organisation/") }); const [name, setName] = useState(""); const [hydrated, setHydrated] = useState(false); if (organisation.data && !hydrated) { setName(organisation.data.name); setHydrated(true); } const update = useMutation({ mutationFn: () => apiRequest<Organisation>("/organisation/", { method: "PATCH", body: { name } }), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["organisation"] }) }); if (organisation.isLoading) return <Spinner />; if (organisation.error || !organisation.data) return <ErrorPanel error={organisation.error} />; const usage = organisation.data.storageLimitBytes ? organisation.data.storageUsedBytes / organisation.data.storageLimitBytes * 100 : 0;
  return <><PageHeader eyebrow="Administration" title="Organisation settings" description="Manage your workspace identity and storage." /><section className="settings-grid"><form className="panel" onSubmit={(e) => { e.preventDefault(); update.mutate(); }}><div className="panel-heading"><div><h2>Workspace details</h2><p>Visible throughout FieldDesk</p></div></div>{update.error && <ErrorPanel error={update.error} />}<div className="form-stack"><label>Organisation name<input value={name} onChange={(e) => setName(e.target.value)} required /></label><label>Workspace slug<input value={organisation.data.slug} disabled /></label><button className="button button-primary align-start">Save settings</button></div></form><div className="panel"><div className="panel-heading"><div><h2>Attachment storage</h2><p>Private organisation allocation</p></div></div><div className="storage-figure"><strong>{formatBytes(organisation.data.storageUsedBytes)}</strong><span>of {formatBytes(organisation.data.storageLimitBytes)} used</span><div><i style={{ width: `${Math.min(100, usage)}%` }} /></div><small>{usage.toFixed(1)}% consumed</small></div></div></section></>;
}

function ProtectedRoutes() { const { session } = useAuth(); if (!session) return <Navigate to="/login" replace />; const manager = session.role !== "technician"; return <AppShell><Routes><Route path="/dashboard" element={<DashboardPage />} /><Route path="/work-orders" element={<WorkOrdersPage />} /><Route path="/work-orders/:id" element={<WorkOrderDetailPage />} />{manager && <Route path="/work-orders/new" element={<WorkOrderFormPage />} />}{manager && <Route path="/work-orders/:id/edit" element={<WorkOrderFormPage edit />} />}{session.role === "owner" && <Route path="/users" element={<UsersPage />} />}{session.role === "owner" && <Route path="/organisation" element={<OrganisationPage />} />}<Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></AppShell>; }
function App() { const { loading } = useAuth(); if (loading) return <main className="boot-screen"><span className="brand-mark large">FD</span><Spinner label="Opening FieldDesk" /></main>; return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/*" element={<ProtectedRoutes />} /></Routes>; }
export default App;
