# Generated by Django 5.2.17 on 2026-09-01 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('storage_key', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organisations.organisation')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to='organisations.organisationuser')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='workorders.workorder')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['organisation', 'work_order', 'created_at'], name='attachments_organis_19c9e3_idx'), models.Index(fields=['organisation', 'checksum_sha256'], name='attachments_organis_662ef4_idx')],
            },
        ),
    ]
