# Generated by Django 5.2.17 on 2026-09-01 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0003_alter_organisation_storage_limit_bytes'),
        ('workorders', '0002_workorder_assignment_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='organisations.organisationuser')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='organisations.organisation')),
                ('related_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='workorders.workorder')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['organisation', 'related_work_order', 'created_at'], name='audit_audit_organis_f0d91c_idx'), models.Index(fields=['organisation', 'target_type', 'target_id'], name='audit_audit_organis_f60f4c_idx'), models.Index(fields=['organisation', 'action', 'created_at'], name='audit_audit_organis_aa27bb_idx')],
            },
        ),
    ]
